package com.google.code.twig;

import junit.framework.Assert;

import org.junit.Test;

import com.google.code.twig.annotation.AnnotationObjectDatastore;
import com.google.code.twig.annotation.Id;

@SuppressWarnings("deprecation")
public class AutoGeneratedIdTest extends LocalDatastoreTestCase
{
	public static class HasStringKey
	{
		@Id String keyField;
	}
	public static class HasIntKey
	{
		@Id int keyField;
	}

	public static class HasLongKey
	{
		@Id Long keyField;
	}
	
	@Test
	public void missingStringField()
	{
		ObjectDatastore datastore = new AnnotationObjectDatastore();
		
		HasStringKey hasNullKey = new HasStringKey();
		boolean failed = false;
		try
		{
			datastore.store(hasNullKey);
		}
		catch (Exception e)
		{
			failed = true;
		}
		Assert.assertTrue(failed);
	}

	@Test
	public void missingIntField()
	{
		ObjectDatastore datastore = new AnnotationObjectDatastore();
		
		HasIntKey hasNullKey = new HasIntKey();
		datastore.store(hasNullKey);
		
		Assert.assertTrue(hasNullKey.keyField > 0);
	}

	@Test
	public void missingLongField()
	{
		ObjectDatastore datastore = new AnnotationObjectDatastore();
		
		HasLongKey hasNullKey = new HasLongKey();
		datastore.store(hasNullKey);
		
		Assert.assertNotNull(hasNullKey.keyField);
	}
	
	
}
